package utils

import (
	"k8s.io/apimachinery/pkg/util/version"
)

var (
	// KubeV1240Alpha4 indicates the version of Kubernetes v1.24.0-alpha.4
	KubeV1240Alpha4 = version.MustParseSemantic("v1.24.0-alpha.4")

	// KubeV1170Beta2 indicates the version of Kubernetes v1.17.0-beta.2
	KubeV1170Beta2 = version.MustParseSemantic("v1.17.0-beta.2")

	// KubeV1210Beta1 indicates the version of Kubernetes v1.21.0-beta.1
	KubeV1210Beta1 = version.MustParseSemantic("v1.21.0-beta.1")
)

// SATokenAutoGenerated is used to indicate whether secret-based service account token can be auto generated
func SATokenAutoGenerated(kubeServerVersion string) (bool, error) {
	parsedVersion, err := version.ParseSemantic(kubeServerVersion)
	if err != nil {
		return false, err
	}

	return parsedVersion.LessThan(KubeV1240Alpha4), nil
}
