variables:
  VERSION: "v3.0.0-alpha"
  REGISTRY: "121.40.102.76:30080"
  APPGAIA: "gaia"
  APPGAIASCHEDULER: "gaia-scheduler"

stages:
  - check
  - build

ci-check:
  stage: check
  image:
    name: ${REGISTRY}/ci/golang-make-lint:alpine-1.23.4
  tags:
    - hyperos
    - cloud
  script:
    - go version
    - go env -w GOPROXY=https://goproxy.cn,direct
    - make fmt-check
    - make lint
    - go mod tidy
  only:
    - merge_requests

debug-image:
  stage: check
  image:
    name: ${REGISTRY}/ci/kaniko-executor:debug
    entrypoint: [""]
  tags:
    - hyperos
    - cloud
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIA}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIA}:${VERSION}-debug"
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIASCHEDULER}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIASCHEDULER}:${VERSION}-debug"
  only:
    - merge_requests

compile-image:
  stage: build
  image:
    name: ${REGISTRY}/ci/kaniko-executor:debug
    entrypoint: [""]
  tags:
    - hyperos
    - cloud
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIA}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIA}:${VERSION}"
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIASCHEDULER}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIASCHEDULER}:${VERSION}"
  only:
    - main
  # - if: $CI_COMMIT_TAG

compile-image-tag:
  stage: build
  image:
    name: ${REGISTRY}/ci/kaniko-executor:debug
    entrypoint: [""]
  tags:
    - hyperos
    - cloud
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIA}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIA}:${CI_COMMIT_TAG}"
    - >-
      /kaniko/executor
      --insecure
      --insecure-registry ${REGISTRY}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target ${APPGAIASCHEDULER}
      --destination "${REGISTRY}/${HARBOR_PROJECT}/${APPGAIASCHEDULER}:${CI_COMMIT_TAG}"
  only:
    - tags
  # - if: $CI_COMMIT_TAG
