apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: group-schedule-example
  namespace: gaia-reserved
  labels:
    apps.gaia.io/user.id: user123_test
spec:
  appID: group-schedule-example
  workloadComponents:
    - componentName: group-component1
      namespace: test
      groupName: group1
      sandbox: runc
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: appcronmaster
        spec:
          containers:
            - name: appcronmastercomp1
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c1/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
    - componentName: group-component2
      namespace: test
      sandbox: runc
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: appserverless-com2
        spec:
          containers:
            - name: appserverless-com2
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c2/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
    - componentName: group-component3
      namespace: test
      sandbox: runc
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: appcronmaster
        spec:
          containers:
            - name: appcronmastercomp1
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c3/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
    - componentName: group-component4
      namespace: test
      sandbox: runc
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: appserverless-com1
        spec:
          containers:
            - name: appserverless-com1
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c4/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
    - componentName: group-component5
      namespace: test
      sandbox: runc
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: app-cronstart
        spec:
          containers:
            - name: appcronstartcomp1
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c5/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
    - componentName: group-component6
      namespace: test
      sandbox: runc
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: appserverless-com1
        spec:
          containers:
            - name: appserverless-com1
              image: 172.17.9.231:8880/hyperio/app:latest
              env:
                - name: SCNID
                  value: "/pml/case1/c6/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
  deploymentCondition:
    mandatory:
      - subject:
          name: group1
          type: group
        object:
          name: geo-location
          type: label
        relation: In
        extent: WyAiQ2hpbmEtSHVhZG9uZy1KaWFuZ3N1LUNpdHktQzExLURpc3RyaWN0LUMxMSIsIkNoaW5hLUh1YWRvbmctSmlhbmdzdS1DaXR5LUMxMS1EaXN0cmljdC1FMTEiXQ== # [ "China-Huadong-Jiangsu-City-C11-District-C11","China-Huadong-Jiangsu-City-C11-District-E11"]
      - subject:
          name: group-component6
          type: component
        object:
          name: geo-location
          type: label
        relation: In
        extent: WyJDaGluYS1IdWFkb25nLUppYW5nc3UtQ2l0eS1DMzEtRGlzdHJpY3QtQzMxIiwiQ2hpbmEtSHVhZG9uZy1KaWFuZ3N1LUNpdHktQzMxLURpc3RyaWN0LUUzMSJdCg== # ["China-Huadong-Jiangsu-City-C31-District-C31","China-Huadong-Jiangsu-City-C31-District-E31"]
  expectedPerformance:
    boundaries:
      inner:
        - name: boundary1
          subject: group-component1
          type: replicas
          value: Mg== # 2
        - name: boundary2
          subject: group-component2
          type: replicas
          value: Mg== # 2
        - name: boundary3
          subject: group-component3
          type: replicas
          value: Mg== # 2
        - name: boundary4
          subject: group-component4
          type: replicas
          value: Mg== # 2
        - name: boundary5
          subject: group-component5
          type: replicas
          value: Mg== # 2
        - name: boundary61
          subject: group-component6
          type: "maxReplicas"
          value: NQ== # 5
        - name: boundary62
          subject: group-component6
          type: "cpu"
          value: MjA= # 20
        - name: boundary63
          subject: group-component6
          type: "cpu"
          value: ODA= # 80
        - name: boundary64
          subject: group-component6
          type: "mem"
          value: MjA= # 20
        - name: boundary65
          subject: group-component6
          type: "mem"
          value: NzA= # 70
        - name: boundary66
          subject: group-component6
          type: "QPS"
          value: MTU= # 15
        - name: boundary67
          subject: group-component6
          type: "QPS"
          value: ODU= # 85
    maintenance:
      hpa:
        - name: "decrease replicas1"
          subject: group-component6
          trigger: boundary62 && boundary64 && boundary66
          strategy:
            type: decrease
            value: MQ== # 1
        - name: "increase replicas1"
          subject: group-component6
          trigger: boundary63 || boundary65 || boundary67
          strategy:
            type: increase
            value: MQ== # 1
