apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: public-app
  namespace: gaia-reserved
  labels:
    apps.gaia.io/user.id: user123
spec:
  appID: public-app
  workloadComponents:
    - componentName: casepublicweather
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicweather
        spec:
          containers:
            - env:
                - name: SCNNUM
                  value: "1"
                - name: SCNID1
                  value: /public/pubappsrv/pubweather/1
              image: 122.96.144.180:30080/ar/life-assistant-weather:latest
              name: casepublicweather
              resources:
                limits:
                  cpu: 1000m
                  memory: 512Mi
                requests:
                  cpu: 1000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
    - componentName: casepublicuserauth
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicuserauth
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubuserauth/1
              image: 122.96.144.180:30080/ar/useragent-scn-http:latest
              name: casepublicuserauth1
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 2000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubuserauth/1
              image: 122.96.144.180:30080/ar/useragent-login:latest
              name: casepublicuserauth2
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 2000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
    - componentName: casepublicdata
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicdata
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubdataauth/1
              image: 122.96.144.180:30080/ar/useragent-data:latest
              name: casepublicdata
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 1000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
    - componentName: casepublicscene
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicscene
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubscenejudge/1
              image: 122.96.144.180:30080/ar/useragent-app:latest
              name: casepublicscene
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 2000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
    - componentName: casepublicaccess
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicaccess
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubcldposplatform/1
              image: 122.96.144.180:30080/ar/ezxr-reloc:latest
              name: casepublicaccess
              resources:
                limits:
                  cpu: 2000m
                  memory: 16384Mi
                requests:
                  cpu: 2000m
                  memory: 16384Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
    - componentName: casepublicidenitify
      sandbox: SecureContainer
      namespace: arpublic
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicidenitify
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubsrvidentify/1
              image: 122.96.144.180:30080/ar/ezxr-identification:latest
              name: casepublicidenitify
              resources:
                limits:
                  cpu: 4000m
                  memory: 16384Mi
                requests:
                  cpu: 4000m
                  memory: 16384Mi
              volumeMounts:
                - mountPath: /tmp
                  name: usock
          hostNetwork: false
          volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: usock
  deploymentCondition:
    mandatory:
      - subject:
          name: casepublicweather
          type: group
        object:
          name: net-enviroment
          type: label
        relation: In
        extent: WyJlZGdlIl0gCg==  # ["edge"]
  expectedPerformance:
    boundaries:
      inner:
        - name: boundary1
          subject: casepublicweather
          type: replicas
          value: MQo= # 1
        - name: boundary2
          subject: casepublicuserauth
          type: replicas
          value: MQo= # 1
        - name: boundary3
          subject: casepublicdata
          type: replicas
          value: MQo= # 1
        - name: boundary4
          subject: casepublicscene
          type: replicas
          value: MQo= # 1
        - name: boundary5
          subject: casepublicidenitify
          type: replicas
          value: MQo= # 1
        - name: boundary6
          subject: casepublicaccess
          type: replicas
          value: MQo= # 1

