apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: public-app
  namespace: gaia-reserved
  labels:
    apps.gaia.io/user.id: admin
spec:
  appID: public-app
  workloadComponents:
    - componentName: casepublicweather
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicweather
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubweather/1
              image: 122.96.144.180:30080/ar/life-assistant-weather:latest
              name: casepublicweather
              resources:
                limits:
                  cpu: 1000m
                  memory: 512Mi
                requests:
                  cpu: 1000m
                  memory: 512Mi
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: false
    - componentName: casepublicuserauth
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicuserauth
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubuserauth/1
              image: 122.96.144.180:30080/ar/useragent-scn-http:v2.0.1
              name: casepublicuserauth1
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 2000m
                  memory: 512Mi
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubuserauth/1
              image: 122.96.144.180:30080/ar/useragent-login:v2.0.1
              name: casepublicuserauth2
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 512Mi
          hostNetwork: false
    - componentName: casepublicdata
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicdata
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubdataauth/1
              image: 122.96.144.180:30080/ar/useragent-data:latest
              name: casepublicdata
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 1000m
                  memory: 512Mi
          hostNetwork: false
    - componentName: casepublicscene
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicscene
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubscenejudge/1
              image: 122.96.144.180:30080/ar/useragent-app:v2.0.1
              name: casepublicscene
              resources:
                limits:
                  cpu: 2000m
                  memory: 512Mi
                requests:
                  cpu: 2000m
                  memory: 512Mi
          hostNetwork: false
    - componentName: casepubliclocate
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepubliclocate
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubcldposplatform/1
              image: 122.96.144.180:30080/ar/ezxr-reloc:latest
              name: casepubliclocate
              resources:
                limits:
                  cpu: 2000m
                  memory: 16384Mi
                requests:
                  cpu: 2000m
                  memory: 16384Mi
          hostNetwork: false
    - componentName: casepublicidenitify
      sandbox: SecureContainer
      namespace: arpublic
      groupName: group1
      workloadType: "stateless-system-service"
      module:
        metadata:
          labels:
            app: casepublicidenitify
        spec:
          containers:
            - env:
                - name: SCNID
                  value: /public/pubappsrv/pubsrvidentify/1
              image: 122.96.144.180:30080/ar/ezxr-identification:latest
              name: casepublicidenitify
              resources:
                limits:
                  cpu: 4000m
                  memory: 16384Mi
                requests:
                  cpu: 4000m
                  memory: 16384Mi
          hostNetwork: false
  deploymentCondition:
    mandatory:
      - subject:
          name: group1
          type: group
        object:
          name: net-environment
          type: label
        relation: In
        extent: WyJlZGdlIl0gCg==  # ["edge"]
      - subject:
          name: group1
          type: group
        object:
          name: geo-location
          type: label
        relation: In
        extent: WyIwMDAwMDAtMDAwMDAxLTMyMDAwMC0zMjAxMDAtMzIwMTA2IiwiMDAwMDAwLTAwMDAwMS0zMjAwMDAtMzIwMTAwLTMyMDExNSJdCg== # ["000000-000001-320000-320100-320106","000000-000001-320000-320100-320115"]
  expectedPerformance:
    boundaries:
      inner:
        - name: boundary1
          subject: casepublicweather
          type: replicas
          value: MQo= # 1
        - name: boundary2
          subject: casepublicuserauth
          type: replicas
          value: MQo= # 1
        - name: boundary3
          subject: casepublicdata
          type: replicas
          value: MQo= # 1
        - name: boundary4
          subject: casepublicscene
          type: replicas
          value: MQo= # 1
        - name: boundary5
          subject: casepublicidenitify
          type: replicas
          value: MQo= # 1
        - name: boundary6
          subject: casepubliclocate
          type: replicas
          value: MQo= # 1

