apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: case5
  namespace: gaia-reserved
spec:
  appID: case5
  components:
    - name: case5-component1
      namespace: test1
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21"] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase5
        spec:
          containers:
            - name: appcase5comp1
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case5/c1/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case5-component2
      namespace: test2
      runtimeType: kata
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: netenviroment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase5
        spec:
          runtimeClassName: kata-containers
          containers:
            - name: appcase5comp2
              image: 172.17.9.231:8880/hyperio/app_kata:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case5/c2/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case5-component3
      namespace: test3
      runtimeType: runc
      dispersion: 2
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C11-District-C11", "China-Huadong-Jiangsu-City-C11-District-E11", "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Alibaba" ] }
        netenvironment:
          matchExpressions:
            - { key: netenviroment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase5
        spec:
          containers:
            - name: appcase5comp3
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case5/c3/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate