apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: case1
  namespace: gaia-reserved
spec:
  appID: case1
  components:
    - name: case1-component1
      namespace: test1
      runtimeType: runc
      workload:
        workloadtype: affinitydaemon
        traitaffinitydaemon:
          sns:
            - 7d1ec81be6bb59cbd3a8609d18cd58c911a8648c
            - 577c0bb88e8ff9e0658749356e01a3767fe5496c
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp1
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c1/1"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case1-component2
      namespace: test2
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp2
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c2/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case1-component3
      namespace: test3
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp3
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c3/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case1-component4
      namespace: test4
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp4
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c4/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case1-component5
      namespace: test5
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp5
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c5/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
    - name: case1-component6
      namespace: test6
      runtimeType: runc
      schedulePolicy:
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "China-Huadong-Jiangsu-City-C21-District-E21", "China-Huadong-Jiangsu-City-C21-District-C21", "China-Huadong-Jiangsu-City-C31-District-C31", "China-Huadong-Jiangsu-City-C31-District-E31" ] }
        provider:
          matchExpressions:
            - { key: provider, operator: In, values: [ "Huawei", "Tencent" ] }
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: appcase1
        spec:
          containers:
            - name: appcase1comp6
              image: 172.17.9.231:8880/hyperio/app:latest
              volumeMounts:
                - mountPath: "/dev/shm"
                  name: "shm"
                - mountPath: "/tmp"
                  name: "usock"
              env:
                - name: SCNID
                  value: "/pml/case1/c6/1"
                - name: IOCLIENT_ADDRESS
                  value:
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"
          volumes:
            - name: shm
              hostPath:
                path: /dev/shm
                type: DirectoryOrCreate
            - name: usock
              hostPath:
                path: /tmp
                type: DirectoryOrCreate